# // TODO: Implementar el docker-compose
services:
  libreria-service:
    container_name: LibreriaService
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 512m
    mem_reservation: 256m
    ports: [ "8080:8080" ]